### ISSUE TITLE
Calorie changes are not retroactive 

### ISSUE THREAD

**Issue by JoESmash** [ttr/tld-WarmFood#2]
Hello,

It would appear that if you set a calorie change to lets say Salmon of 1.2 and then start a game and find a salmon in a fridge and the salmon has a calorie value of 2600 or so, which you may feel is ridiculously high. So you go to the mod settings and lower the value to "1," or remove the mod entirely, the salmon remains at 2600 or so. 

I guess it can only be changed by starting a new game over again.

**Comment by ttr** [comment]
This is actually how it supposed to be - those values are applied on new items only. There is/was way of reset them by re-loading scene when item is on a ground.
